version: '3.6'
name: nextjs_vps_test
services:
    rds:
        image: postgres
        container_name: db
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: 'admin'
            POSTGRES_DB: 'nextjs_vps_test'
        command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on

    minio:
        image: quay.io/minio/minio:latest
        container_name: s3-minio
        environment:
            MINIO_ROOT_USER: admin123
            MINIO_ROOT_PASSWORD: admin123
        command: server --console-address ":9090" /data
        volumes:
            - ./minio/data:/data
            - ./docker/minio/export:/export
        ports:
            - 9000:9000
            - 9090:9090
    mc:
        image: minio/mc
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc alias set s3-minio http://minio:9000 admin123 admin123;
            /usr/bin/mc mb s3-minio/sample --region=ap-northeast-1;
            /usr/bin/mc policy set public s3-minio/sample;
            exit 0;
            "