version: '3.6'
name: nextjs_vps_test
services:
    rds:
        image: postgres
        container_name: rdb
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: 'admin'
            POSTGRES_DB: 'nextjs_vps_test'
        command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
