name: CD
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install SSH Key for Deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          key: ${{ secrets.VPS_SSH_KEY }}
          host: ${{ secrets.VPS_HOST_NAME }}
          username: ${{ secrets.VPS_SSH_USER }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            cd /var/git/nextjs_vps_test/
            git pull
            cp -r /var/git/nextjs_vps_test/* /home/dev/projects/nextjs_vps_test
